import { geminiProvider } from "../GeminiProvider";

const testGeminiIntegration = async () => {
  console.log("🤖 Testing Gemini API integration with configured GEMINI_MODEL...");
  console.log(`  Configured Model: ${geminiProvider.getModelName()}`);

  const prompt = "Deconstruct query into step plan: Investigate Tesla market position and report executive summary";
  const result = await geminiProvider.generateJSON(prompt);

  console.log("  Received Generated Plan:", JSON.stringify(result, null, 2));

  if (!result || !(result as any).steps || !Array.isArray((result as any).steps)) {
    throw new Error("Invalid plan generated by GeminiProvider");
  }

  console.log("✅ Gemini API integration test PASSED!");
};

testGeminiIntegration().catch((err) => {
  console.error("❌ Gemini API test failed:", err);
  process.exit(1);
});
