export const DISTRIBUTED_CONFIG = {
  defaultMaxRetries: 3,
  defaultQueueDepth: 1000,
  defaultWorkerConcurrency: 5,
  lockLeaseDurationMs: 30000,
  workerHeartbeatIntervalMs: 10000,
  workerOfflineTimeoutMs: 30000,
  queueNames: [
    "high-priority",
    "execution",
    "planner",
    "marketplace",
    "agents",
    "learning",
    "optimization",
    "analytics",
    "default",
  ],
  jobCategories: [
    "EXECUTION",
    "PLANNER",
    "MARKETPLACE",
    "LEARNING",
    "INTELLIGENCE",
    "OPTIMIZATION",
    "SYSTEM",
    "ANALYTICS",
    "MAINTENANCE",
  ],
};
