export enum JobStatusEnum {
  QUEUED = "QUEUED",
  DISPATCHED = "DISPATCHED",
  RUNNING = "RUNNING",
  RETRYING = "RETRYING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  DEAD_LETTER = "DEAD_LETTER",
  CANCELLED = "CANCELLED",
}
