export enum RequestStateEnum {
  RECEIVED = "RECEIVED",
  AUTHENTICATED = "AUTHENTICATED",
  AUTHORIZED = "AUTHORIZED",
  VALIDATED = "VALIDATED",
  ROUTED = "ROUTED",
  FORWARDED = "FORWARDED",
  RESPONDED = "RESPONDED",
  FAILED = "FAILED",
}

export enum ServiceHealthEnum {
  HEALTHY = "HEALTHY",
  DEGRADED = "DEGRADED",
  UNHEALTHY = "UNHEALTHY",
  OFFLINE = "OFFLINE",
}
