export enum RoutingAlgorithmEnum {
  ROUND_ROBIN = "ROUND_ROBIN",
  LEAST_CONNECTIONS = "LEAST_CONNECTIONS",
  WEIGHTED_RANDOM = "WEIGHTED_RANDOM",
  CANARY = "CANARY",
}

export enum GatewayPolicyScopeEnum {
  GLOBAL = "GLOBAL",
  TENANT = "TENANT",
  ORGANIZATION = "ORGANIZATION",
  WORKSPACE = "WORKSPACE",
  ENDPOINT = "ENDPOINT",
}
