export const ROUTES = {
  AUTH: {
    LOGIN: "/login",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    SESSION_EXPIRED: "/session-expired",
    UNAUTHORIZED: "/unauthorized",
    FORBIDDEN: "/forbidden",
  },
  DASHBOARD: "/dashboard",
  MERCHANTS: {
    LIST: "/merchants",
    DETAILS: (id: string) => `/merchants/${id}`,
  },
  RESEARCH: "/research",
  TRANSACTIONS: {
    LIST: "/transactions",
    DETAILS: (id: string) => `/transactions/${id}`,
  },
  POLICIES: "/policies",
  SERVICES: "/services",
  AUDIT: "/audit",
  ANALYTICS: "/analytics",
  HEALTH: "/health",
  SETTINGS: "/settings",
  PLANNER: "/planner",
  EXECUTION: "/execution",
  MARKETPLACE: "/marketplace",
  AGENTS: "/agents",
  INTELLIGENCE: "/intelligence",
  CONTROL_PLANE: "/control-plane",
  DISTRIBUTED: "/distributed",
  GATEWAY: "/gateway",
  OBSERVABILITY: "/observability",
  SECURITY: "/security",
  DEVOPS: "/devops",
  PRODUCTION: "/production",
  BAZAAR: {
    DISCOVERY: "/bazaar",
    SERVICES: "/bazaar/services",
    PROVIDERS: "/bazaar/providers",
  },
  SYSTEM: {
    NOT_FOUND: "/not-found",
    MAINTENANCE: "/maintenance",
    ERROR: "/error",
  },
} as const;
